import dynamic from "next/dynamic";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useAccount } from "wagmi";
import Masonry, { ResponsiveMasonry } from "react-responsive-masonry";

const GenerateMessageBtn = dynamic(
  () => import("~/components/GenerateMessageBtn"),
  {
    ssr: false,
  },
);

export default function Home() {
  const { address } = useAccount();
  const [data, setData] = useState<any[]>([]);

  useEffect(() => {
    if (!address) return;
    const eventSource = new EventSource("http://localhost:3001/nfts", {
      withCredentials: true,
    });

    eventSource.onmessage = (event) => {
      const newData = JSON.parse(event.data);

      setData((prevState) => [...prevState, newData]);
    };

    eventSource.onerror = (error) => {
      console.error("EventSource failed:", error);
      eventSource.close();
    };

    return () => {
      eventSource.close();
    };
  }, [address]);

  return (
    <>
      <Head>
        <title>Gllry</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center ">
        <GenerateMessageBtn />

        <section className="mt-12 grid max-w-5xl grid-cols-1 gap-16 p-8 md:grid-cols-2">
          {data.map((item, idx) => (
            <div key={idx}>
              <img
                loading="lazy"
                decoding="async"
                src={item.media[0].gateway}
                className="min-w-[275px] rounded-3xl shadow-2xl transition duration-150 ease-in-out hover:scale-105"
              />
              <h2 className="my-8 block">{item.title}</h2>

              <p>{item.description}</p>
            </div>
          ))}
        </section>
      </main>
    </>
  );
}
